server:
    port : 8080
    
spring:
   application:
      name: DEPARTMENT-SERVICE
    
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
      registerWithEureka: true
      fetchRegistry: true
