server:
  port : 8081
 
spring:
   application:
      name: USER-SERVICE
       
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
      instance:
      preferIpAddress: true
      registerWithEureka: true
      fetchRegistry: true
      
